/**
 * Offline self-test — no DSH, no API key, no network, no browser.
 *
 * It pins the behaviours that were broken before v0.1.1:
 *   1. a folder that has never been scanned gets its whole history backfilled
 *      (per-directory anchors instead of one global window);
 *   2. the next scan of that folder is incremental and idempotent;
 *   3. a folder whose scan was interrupted does NOT get its anchor advanced;
 *   4. search finds a file when only its *content* carries the keyword — the
 *      "the file name says horse, the picture shows a whale" regression;
 *   5. the "database location" box tolerates a folder (v0.1.3) — a folder must
 *      normalise to index.db inside it instead of blowing up the whole scan.
 *
 * Run: node tools/selftest.mjs   (or: npm test)
 */
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { DEFAULT_CONFIG, buildExcludes, defaultDbPath, resolveDbPath } from "../config.mjs";
import { counts, markRootScanned, openDb, syncRoots, upsertFile } from "../db.mjs";
import { rootSinceMs } from "../core/schedule.mjs";
import { scanRoots } from "../core/scan.mjs";
import { searchFiles } from "../core/search.mjs";

const OVERLAP_MS = 6 * 3600 * 1000;
const tmp = mkdtempSync(join(tmpdir(), "laf-selftest-"));
let passed = 0;
const ok = (name) => { passed++; console.log(`  ok  ${name}`); };

async function collect(db, roots, sinceMs, signal) {
  const stats = { added: 0, updated: 0 };
  const result = await scanRoots({
    roots,
    excludes: buildExcludes({ ...DEFAULT_CONFIG }),
    sinceMs,
    signal,
    onCandidate(rec) {
      stats[upsertFile(db, rec) === "added" ? "added" : "updated"]++;
    },
  });
  return { stats, result };
}

try {
  const rootA = join(tmp, "rootA");
  mkdirSync(join(rootA, "sub"), { recursive: true });
  writeFileSync(join(rootA, "a.md"), "# alpha\n");
  writeFileSync(join(rootA, "b.txt"), "beta\n");
  writeFileSync(join(rootA, "sub", "c.json"), "{}\n");

  const db = openDb(join(tmp, "index.db"));
  const roots = [{ path: rootA, policy: "full" }];
  syncRoots(db, roots);

  // 1) a folder that has never been scanned is collected from the beginning of time
  const since1 = rootSinceMs({ db, root: roots[0], config: { firstScanMode: "full" } });
  assert.equal(since1, 0, "a never-scanned folder must be backfilled in full");
  const run1 = await collect(db, [{ ...roots[0], sinceMs: since1 }], since1);
  assert.equal(run1.stats.added, 3, "all three files must be indexed");
  assert.equal(counts(db).total, 3);
  assert.equal(run1.result.roots[0].completed, true);
  ok("first scan of a new folder backfills its whole history (3 files)");

  // 2) once the anchor is advanced the folder goes incremental, and stays idempotent
  const scanStart = Date.now();
  markRootScanned(db, rootA, scanStart);
  const since2 = rootSinceMs({ db, root: roots[0], config: { firstScanMode: "full" } });
  assert.equal(since2, scanStart - OVERLAP_MS, "an already-scanned folder uses its own anchor minus the overlap window");
  const run2 = await collect(db, [{ ...roots[0], sinceMs: since2 }], since2);
  assert.equal(run2.stats.added, 0, "the second scan must not add anything again");
  assert.equal(counts(db).total, 3);
  ok("second scan is incremental and idempotent (0 added)");

  // 3) a folder whose scan was interrupted keeps its anchor for the next run
  const rootB = join(tmp, "rootB");
  mkdirSync(rootB, { recursive: true });
  for (let i = 0; i < 50; i++) writeFileSync(join(rootB, `f${i}.txt`), "x\n");
  syncRoots(db, [roots[0], { path: rootB, policy: "full" }]);
  const ac = new AbortController();
  const run3 = await scanRoots({
    roots: [{ path: rootA, sinceMs: 0 }, { path: rootB, sinceMs: 0 }],
    excludes: buildExcludes({ ...DEFAULT_CONFIG }),
    sinceMs: 0,
    signal: ac.signal,
    onCandidate() { ac.abort(); },
  });
  assert.equal(run3.roots[0].completed, false, "an aborted folder must be reported as not completed");
  ok("an interrupted folder is reported completed=false (anchor kept)");

  // 4) content-only hit: the name says horse, the picture shows a whale
  upsertFile(db, {
    path: join(rootA, "cartoon-horse.png"), root: rootA, name: "cartoon-horse.png",
    ext: ".png", size: 1024, birth_ms: scanStart, mtime_ms: scanStart, appeared_ms: scanStart,
    category: "图片", origin: "未知", policy: "full", noise: 0, first_seen_ms: scanStart,
  });
  db.prepare("UPDATE files SET image_desc = ? WHERE name = ?")
    .run("hollow knight riding a whale, underwater light shafts, generated by doubao", "cartoon-horse.png");
  const found = await searchFiles(db, { keywords: "knight whale" });
  assert.ok(
    found.rows.some((r) => r.name === "cartoon-horse.png"),
    "words that only exist in the content must still find the file",
  );
  ok("a content-only hit is found even when the file name has none of the words");

  // 5) the "database location" box may hold a folder — it must normalise to a file inside it
  const dbFolder = join(tmp, "dbfolder");
  mkdirSync(dbFolder, { recursive: true });
  assert.equal(resolveDbPath({ dbPath: dbFolder }), join(dbFolder, "index.db"),
    "an existing folder must resolve to index.db inside it");
  assert.equal(resolveDbPath({ dbPath: dbFolder + "\\" }), join(dbFolder, "index.db"),
    "a trailing separator must be treated as a folder");
  assert.equal(resolveDbPath({ dbPath: join(dbFolder, "custom.db") }), join(dbFolder, "custom.db"),
    "an explicit file path must be kept as-is");
  assert.equal(resolveDbPath({ dbPath: "" }), defaultDbPath(),
    "an empty value must fall back to the default location");
  ok("a folder given as the database location resolves to index.db inside it");

  db.close();
  console.log(`\nself-test passed: ${passed}/5`);
} catch (e) {
  console.error("\nself-test FAILED:", (e && e.message) || e);
  process.exitCode = 1;
} finally {
  try { rmSync(tmp, { recursive: true, force: true }); } catch { /* ignore */ }
}
